building blocks scss
collabo-community/building-blocks pull request #1
Opened 2024-06-28 12:01 UTC by Akpjunior94

Transpile scss to css

2024-06-28 12:29 UTC, Ifycode requested changes
Nice @Akpjunior94 
PR is awesome - takes care of file structure too.

But if you rename a file, the css.map file for the old one still remains. Let's remove that.

2024-06-30 22:47 UTC, Akpjunior94 commented
> Nice @Akpjunior94 PR is awesome - takes care of file structure too.
> 
> But if you rename a file, the css.map file for the old one still remains. Let's remove that.

@Ifycode You can now check again. pushed an update.

2024-07-01 04:33 UTC, Ifycode requested changes

2024-07-01 04:33 UTC, Ifycode commented on watch-delete.js
> +    }
Hmm... Interesting fix altogether with chokidar... @Akpjunior94
Although since SCSS already deletes CSS files maybe it shouldn't try to still delete it. What if the watch only initiates the delete of a `.css.map` file in the case where it doesn't find a corresponding `.css` file with the same name?

2024-07-01 05:12 UTC, Akpjunior94 commented on watch-delete.js
> +    }
You right.  it still does the same thing. there is no need for the deletion of css since it has already being handled by SCSS. will remove that line of code.

2024-07-01 05:24 UTC, Akpjunior94 commented on watch-delete.js
> +    }
@Ifycode updated.

2024-07-02 12:33 UTC, Ifycode commented on watch-delete.js
> +      console.log(`Deleted ${cssMapPath}`);
We may reconsider if we should keep on going with this watcher/chokidar approach later.
Works for now, so we use it.

2024-07-02 12:34 UTC, merged